api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "quantity-discount"
type = "function"
uid = "37d9f684-b180-67a1-d416-f5a8b854ddb0e359a4d5"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
