api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "bundle-transform"
type = "function"
uid = "3bce9038-da6c-a56e-c2fa-d26f4b5bf7aeb8d94064"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
